#
## Cluster
##
#[all:vars]
#cluster_name=cluster.local
#native_dns=os.ncsa.edu
#key_name= iassist1
#image= CoreOSAlpha
#flavor= m1.medium
#kube_version= 1.2.4
#kube-ui= true
#kube-dash= true
##
## Servers
##
#[masters]
#iassist1-master1
#
#[etcd:children]
#masters
#
#[glfs]
#iassist1-gfs[1:2]
#
#[compute]
#iassist1-node[1:4]
#
#[loadbal]
#iassist1-loadbal
#
##
## Groups - assigned according to roles
##
#
##Compute nodes
#[nodes:children]
#glfs
#compute
#loadbal
#
##all nodes
#[cluster:children]
#nodes
#masters
#etcd
#
#[all:children]
#cluster
#
#[openstack:children]
#cluster
#[coreos:children]
#cluster
#[publicip:children]
#loadbal
#
##
## Cluster-Specific Group Variables/overrides
##
#[glfs:vars]
#vol_size= 200
#vol_name= brick0
#mount_path= /media/brick0
#service_name=media-brick0.mount
#
#[compute:vars]
#flavor=n-rcd1.large
